version: '3'

services:
    app:
        build:
            context: ./node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node index.js
        networks:
            - node-network
        volumes:
            - ./node:/usr/src/app
            - /usr/src/app/node_modules
        tty: true
        depends_on:
            - db
        ports:
            - "3306"

    db:
        build:
            context: ./mysql
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        environment: 
            - MYSQL_DATABASE=node_db
            - MYSQL_ROOT_PASSWORD=root
        networks:
           - node-network
            #incluída a localização da pasta mysql e da porta de comunicação
        volumes:
            - /var/lib/mysql
        ports:
            - "3306:3306"
    nginx:
        build:
        #incremento datag dockerfile
            dockerfile: ./nginx
            context: .
        image: javielrezende/nginx
        container_name: nginx
        depends_on:
            - app
        ports: 
            - "8000:80"
        networks:
            - node-network
#criando variavel node-network que estava faltando
networks:
    node-network:
            driver: bridge